version: '3'
services:
  fragenevaluierung:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10.0.0.26:5001:5001"
    depends_on:
      - consul

  consul:
    image: consul
    ports:
      - 8500:8500
