version: "3"
services:
  fragenevaluierung1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - SERVICE_NAME=fragenevaluierung
      - SERVICE_TAGS=tag1,tag2

  fragenevaluierung2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - SERVICE_NAME=fragenevaluierung
      - SERVICE_TAGS=tag1,tag2
